package Net::AFP::TextEncodings;

use strict;
use warnings;
use Readonly;

Readonly our $kTextEncodingMacRoman             => 0;
Readonly our $kTextEncodingMacJapanese          => 1;
Readonly our $kTextEncodingMacChineseTrad       => 2;
Readonly our $kTextEncodingMacKorean            => 3;
Readonly our $kTextEncodingMacArabic            => 4;
Readonly our $kTextEncodingMacHebrew            => 5;
Readonly our $kTextEncodingMacGreek             => 6;
Readonly our $kTextEncodingMacCyrillic          => 7;
Readonly our $kTextEncodingMacDevanagari        => 9;
Readonly our $kTextEncodingMacGurmukhi          => 10;
Readonly our $kTextEncodingMacGujarati          => 11;
Readonly our $kTextEncodingMacOriya             => 12;
Readonly our $kTextEncodingMacBengali           => 13;
Readonly our $kTextEncodingMacTamil             => 14;
Readonly our $kTextEncodingMacTelugu            => 15;
Readonly our $kTextEncodingMacKannada           => 16;
Readonly our $kTextEncodingMacMalayalam         => 17;
Readonly our $kTextEncodingMacSinhalese         => 18;
Readonly our $kTextEncodingMacBurmese           => 19;
Readonly our $kTextEncodingMacKhmer             => 20;
Readonly our $kTextEncodingMacThai              => 21;
Readonly our $kTextEncodingMacLaotian           => 22;
Readonly our $kTextEncodingMacGeorgian          => 23;
Readonly our $kTextEncodingMacArmenian          => 24;
Readonly our $kTextEncodingMacChineseSimp       => 25;
Readonly our $kTextEncodingMacTibetan           => 26;
Readonly our $kTextEncodingMacMongolian         => 27;
Readonly our $kTextEncodingMacEthiopic          => 28;
Readonly our $kTextEncodingMacCentralEurRoman   => 29;
Readonly our $kTextEncodingMacVietnamese        => 30;
Readonly our $kTextEncodingMacExtArabic         => 31;
Readonly our $kTextEncodingMacSymbol            => 33;
Readonly our $kTextEncodingMacDingbats          => 34;
Readonly our $kTextEncodingMacTurkish           => 35;
Readonly our $kTextEncodingMacCroatian          => 36;
Readonly our $kTextEncodingMacIcelandic         => 37;
Readonly our $kTextEncodingMacRomanian          => 38;
Readonly our $kTextEncodingMacCeltic            => 39;
Readonly our $kTextEncodingMacGaelic            => 40;
Readonly our $kTextEncodingMacKeyboardGlyphs    => 41;
Readonly our $kTextEncodingMacUnicode           => 126;
Readonly our $kTextEncodingMacFarsi             => 140;
Readonly our $kTextEncodingMacUkrainian         => 152;
Readonly our $kTextEncodingMacInuit             => 236;
Readonly our $kTextEncodingMacVT100             => 252;
Readonly our $kTextEncodingMacHFS               => 255;
Readonly our $kTextEncodingUnicodeDefault       => 256;
Readonly our $kTextEncodingUnicodeV1_1          => 257;
Readonly our $kTextEncodingISO10646_1993        => 257;
Readonly our $kTextEncodingUnicodeV2_0          => 259;
Readonly our $kTextEncodingUnicodeV2_1          => 259;
Readonly our $kTextEncodingUnicodeV3_0          => 260;
Readonly our $kTextEncodingISOLatin1            => 513;
Readonly our $kTextEncodingISOLatin2            => 514;
Readonly our $kTextEncodingISOLatin3            => 515;
Readonly our $kTextEncodingISOLatin4            => 516;
Readonly our $kTextEncodingISOLatinCyrillic     => 517;
Readonly our $kTextEncodingISOLatinArabic       => 518;
Readonly our $kTextEncodingISOLatinGreek        => 519;
Readonly our $kTextEncodingISOLatinHebrew       => 520;
Readonly our $kTextEncodingISOLatin5            => 521;
Readonly our $kTextEncodingISOLatin6            => 522;
Readonly our $kTextEncodingISOLatin7            => 525;
Readonly our $kTextEncodingISOLatin8            => 526;
Readonly our $kTextEncodingISOLatin9            => 527;
Readonly our $kTextEncodingDOSLatinUS           => 1024;
Readonly our $kTextEncodingDOSGreek             => 1029;
Readonly our $kTextEncodingDOSBalticRim         => 1030;
Readonly our $kTextEncodingDOSLatin1            => 1040;
Readonly our $kTextEncodingDOSGreek1            => 1041;
Readonly our $kTextEncodingDOSLatin2            => 1042;
Readonly our $kTextEncodingDOSCyrillic          => 1043;
Readonly our $kTextEncodingDOSTurkish           => 1044;
Readonly our $kTextEncodingDOSPortuguese        => 1045;
Readonly our $kTextEncodingDOSIcelandic         => 1046;
Readonly our $kTextEncodingDOSHebrew            => 1047;
Readonly our $kTextEncodingDOSCanadianFrench    => 1048;
Readonly our $kTextEncodingDOSArabic            => 1049;
Readonly our $kTextEncodingDOSNordic            => 1050;
Readonly our $kTextEncodingDOSRussian           => 1051;
Readonly our $kTextEncodingDOSGreek2            => 1052;
Readonly our $kTextEncodingDOSThai              => 1053;
Readonly our $kTextEncodingDOSJapanese          => 1056;
Readonly our $kTextEncodingDOSChineseSimplif    => 1057;
Readonly our $kTextEncodingDOSKorean            => 1058;
Readonly our $kTextEncodingDOSChineseTrad       => 1059;
Readonly our $kTextEncodingWindowsLatin1        => 1280;
Readonly our $kTextEncodingWindowsANSI          => 1280;
Readonly our $kTextEncodingWindowsLatin2        => 1281;
Readonly our $kTextEncodingWindowsCyrillic      => 1282;
Readonly our $kTextEncodingWindowsGreek         => 1283;
Readonly our $kTextEncodingWindowsLatin5        => 1284;
Readonly our $kTextEncodingWindowsHebrew        => 1285;
Readonly our $kTextEncodingWindowsArabic        => 1286;
Readonly our $kTextEncodingWindowsBalticRim     => 1287;
Readonly our $kTextEncodingWindowsVietnamese    => 1288;
Readonly our $kTextEncodingWindowsKoreanJohab   => 1296;
Readonly our $kTextEncodingUS_ASCII             => 1536;
Readonly our $kTextEncodingJIS_X0201_76         => 1568;
Readonly our $kTextEncodingJIS_X0208_83         => 1569;
Readonly our $kTextEncodingJIS_X0208_90         => 1570;

# Translation of known Mac charset IDs to Perl encoding IDs.
our %encmap = (
                $kTextEncodingMacRoman            => q{MacRoman},
                $kTextEncodingMacJapanese         => q{macJapanese},
                $kTextEncodingMacChineseTrad      => q{MacChineseTrad},
                $kTextEncodingMacKorean           => q{MacKorean},
                $kTextEncodingMacArabic           => q{MacArabic},
                $kTextEncodingMacHebrew           => q{MacHebrew},
                $kTextEncodingMacGreek            => q{MacGreek},
                $kTextEncodingMacCyrillic         => q{MacCyrillic},
                $kTextEncodingMacThai             => q{MacThai},
                $kTextEncodingMacChineseSimp      => q{MacChineseSimp},
                $kTextEncodingMacCentralEurRoman  => q{MacCentralEurRoman},
                $kTextEncodingMacVietnamese       => q{MacVietnamese},
                $kTextEncodingMacSymbol           => q{MacSymbol},
                $kTextEncodingMacDingbats         => q{MacDingbats},
                $kTextEncodingMacTurkish          => q{MacTurkish},
                $kTextEncodingMacCroatian         => q{MacCroatian},
                $kTextEncodingMacIcelandic        => q{MacIcelandic},
                $kTextEncodingMacRomanian         => q{MacRomanian},
                $kTextEncodingMacFarsi            => q{MacFarsi},
                $kTextEncodingMacUkrainian        => q{MacUkrainian},
                $kTextEncodingISOLatin1           => q{iso-8859-1},
                $kTextEncodingISOLatin2           => q{iso-8859-2},
                $kTextEncodingISOLatin3           => q{iso-8859-3},
                $kTextEncodingISOLatin4           => q{iso-8859-4},
                $kTextEncodingISOLatinCyrillic    => q{iso-8859-5},
                $kTextEncodingISOLatinArabic      => q{iso-8859-6},
                $kTextEncodingISOLatinGreek       => q{iso-8859-7},
                $kTextEncodingISOLatinHebrew      => q{iso-8859-8},
                $kTextEncodingISOLatin5           => q{iso-8859-9},
                $kTextEncodingISOLatin6           => q{iso-8859-10},
                $kTextEncodingISOLatin7           => q{iso-8859-13},
                $kTextEncodingISOLatin8           => q{iso-8859-14},
                $kTextEncodingISOLatin9           => q{iso-8859-15},
                $kTextEncodingDOSLatinUS          => q{cp437},
                $kTextEncodingDOSGreek            => q{cp737},
                $kTextEncodingDOSBalticRim        => q{cp775},
                $kTextEncodingDOSLatin1           => q{cp850},
                $kTextEncodingDOSLatin2           => q{cp852},
                $kTextEncodingDOSCyrillic         => q{cp855},
                $kTextEncodingDOSTurkish          => q{cp857},
                $kTextEncodingDOSPortuguese       => q{cp860},
                $kTextEncodingDOSIcelandic        => q{cp861},
                $kTextEncodingDOSHebrew           => q{cp862},
                $kTextEncodingDOSArabic           => q{cp864},
                $kTextEncodingDOSNordic           => q{cp865},
                $kTextEncodingDOSGreek2           => q{cp869},
                $kTextEncodingDOSThai             => q{cp874},
                $kTextEncodingDOSJapanese         => q{cp932},
                $kTextEncodingDOSChineseSimplif   => q{cp936},
                $kTextEncodingDOSKorean           => q{cp949},
                $kTextEncodingDOSChineseTrad      => q{cp950},
                $kTextEncodingWindowsLatin1       => q{cp1252},
                $kTextEncodingWindowsLatin2       => q{cp1250},
                $kTextEncodingWindowsCyrillic     => q{cp1251},
                $kTextEncodingWindowsGreek        => q{cp1253},
                $kTextEncodingWindowsLatin5       => q{cp1254},
                $kTextEncodingWindowsHebrew       => q{cp1255},
                $kTextEncodingWindowsArabic       => q{cp1256},
                $kTextEncodingWindowsBalticRim    => q{cp1257},
                $kTextEncodingWindowsVietnamese   => q{cp1258},
                $kTextEncodingUS_ASCII            => q{US-ASCII},
                $kTextEncodingJIS_X0201_76        => q{jis0201-raw},
                $kTextEncodingJIS_X0208_83        => q{jis0208-raw},
              );

1;
# vim: ts=4
