package Net::AFP::TextEncodings;

use strict;
use warnings;
use Readonly;

Readonly our $kTextEncodingMacRoman             => 0;
Readonly our $kTextEncodingMacJapanese          => 1;
Readonly our $kTextEncodingMacChineseTrad       => 2;
Readonly our $kTextEncodingMacKorean            => 3;
Readonly our $kTextEncodingMacArabic            => 4;
Readonly our $kTextEncodingMacHebrew            => 5;
Readonly our $kTextEncodingMacGreek             => 6;
Readonly our $kTextEncodingMacCyrillic          => 7;
Readonly our $kTextEncodingMacDevanagari        => 9;
Readonly our $kTextEncodingMacGurmukhi          => 10;
Readonly our $kTextEncodingMacGujarati          => 11;
Readonly our $kTextEncodingMacOriya             => 12;
Readonly our $kTextEncodingMacBengali           => 13;
Readonly our $kTextEncodingMacTamil             => 14;
Readonly our $kTextEncodingMacTelugu            => 15;
Readonly our $kTextEncodingMacKannada           => 16;
Readonly our $kTextEncodingMacMalayalam         => 17;
Readonly our $kTextEncodingMacSinhalese         => 18;
Readonly our $kTextEncodingMacBurmese           => 19;
Readonly our $kTextEncodingMacKhmer             => 20;
Readonly our $kTextEncodingMacThai              => 21;
Readonly our $kTextEncodingMacLaotian           => 22;
Readonly our $kTextEncodingMacGeorgian          => 23;
Readonly our $kTextEncodingMacArmenian          => 24;
Readonly our $kTextEncodingMacChineseSimp       => 25;
Readonly our $kTextEncodingMacTibetan           => 26;
Readonly our $kTextEncodingMacMongolian         => 27;
Readonly our $kTextEncodingMacEthiopic          => 28;
Readonly our $kTextEncodingMacCentralEurRoman   => 29;
Readonly our $kTextEncodingMacVietnamese        => 30;
Readonly our $kTextEncodingMacExtArabic         => 31;
Readonly our $kTextEncodingMacSymbol            => 33;
Readonly our $kTextEncodingMacDingbats          => 34;
Readonly our $kTextEncodingMacTurkish           => 35;
Readonly our $kTextEncodingMacCroatian          => 36;
Readonly our $kTextEncodingMacIcelandic         => 37;
Readonly our $kTextEncodingMacRomanian          => 38;
Readonly our $kTextEncodingMacCeltic            => 39;
Readonly our $kTextEncodingMacGaelic            => 40;
Readonly our $kTextEncodingMacKeyboardGlyphs    => 41;
Readonly our $kTextEncodingMacUnicode           => 126;
Readonly our $kTextEncodingMacFarsi             => 140;
Readonly our $kTextEncodingMacUkrainian         => 152;
Readonly our $kTextEncodingMacInuit             => 236;
Readonly our $kTextEncodingMacVT100             => 252;
Readonly our $kTextEncodingMacHFS               => 255;
Readonly our $kTextEncodingUnicodeDefault       => 256;
Readonly our $kTextEncodingUnicodeV1_1          => 257;
Readonly our $kTextEncodingISO10646_1993        => 257;
Readonly our $kTextEncodingUnicodeV2_0          => 259;
Readonly our $kTextEncodingUnicodeV2_1          => 259;
Readonly our $kTextEncodingUnicodeV3_0          => 260;
Readonly our $kTextEncodingISOLatin1            => 513;
Readonly our $kTextEncodingISOLatin2            => 514;
Readonly our $kTextEncodingISOLatin3            => 515;
Readonly our $kTextEncodingISOLatin4            => 516;
Readonly our $kTextEncodingISOLatinCyrillic     => 517;
Readonly our $kTextEncodingISOLatinArabic       => 518;
Readonly our $kTextEncodingISOLatinGreek        => 519;
Readonly our $kTextEncodingISOLatinHebrew       => 520;
Readonly our $kTextEncodingISOLatin5            => 521;
Readonly our $kTextEncodingISOLatin6            => 522;
Readonly our $kTextEncodingISOLatin7            => 525;
Readonly our $kTextEncodingISOLatin8            => 526;
Readonly our $kTextEncodingISOLatin9            => 527;
Readonly our $kTextEncodingDOSLatinUS           => 1024;
Readonly our $kTextEncodingDOSGreek             => 1029;
Readonly our $kTextEncodingDOSBalticRim         => 1030;
Readonly our $kTextEncodingDOSLatin1            => 1040;
Readonly our $kTextEncodingDOSGreek1            => 1041;
Readonly our $kTextEncodingDOSLatin2            => 1042;
Readonly our $kTextEncodingDOSCyrillic          => 1043;
Readonly our $kTextEncodingDOSTurkish           => 1044;
Readonly our $kTextEncodingDOSPortuguese        => 1045;
Readonly our $kTextEncodingDOSIcelandic         => 1046;
Readonly our $kTextEncodingDOSHebrew            => 1047;
Readonly our $kTextEncodingDOSCanadianFrench    => 1048;
Readonly our $kTextEncodingDOSArabic            => 1049;
Readonly our $kTextEncodingDOSNordic            => 1050;
Readonly our $kTextEncodingDOSRussian           => 1051;
Readonly our $kTextEncodingDOSGreek2            => 1052;
Readonly our $kTextEncodingDOSThai              => 1053;
Readonly our $kTextEncodingDOSJapanese          => 1056;
Readonly our $kTextEncodingDOSChineseSimplif    => 1057;
Readonly our $kTextEncodingDOSKorean            => 1058;
Readonly our $kTextEncodingDOSChineseTrad       => 1059;
Readonly our $kTextEncodingWindowsLatin1        => 1280;
Readonly our $kTextEncodingWindowsANSI          => 1280;
Readonly our $kTextEncodingWindowsLatin2        => 1281;
Readonly our $kTextEncodingWindowsCyrillic      => 1282;
Readonly our $kTextEncodingWindowsGreek         => 1283;
Readonly our $kTextEncodingWindowsLatin5        => 1284;
Readonly our $kTextEncodingWindowsHebrew        => 1285;
Readonly our $kTextEncodingWindowsArabic        => 1286;
Readonly our $kTextEncodingWindowsBalticRim     => 1287;
Readonly our $kTextEncodingWindowsVietnamese    => 1288;
Readonly our $kTextEncodingWindowsKoreanJohab   => 1296;
Readonly our $kTextEncodingUS_ASCII             => 1536;
Readonly our $kTextEncodingJIS_X0201_76         => 1568;
Readonly our $kTextEncodingJIS_X0208_83         => 1569;
Readonly our $kTextEncodingJIS_X0208_90         => 1570;

# Translation of known Mac charset IDs to Perl encoding IDs.
our %encmap = (
                $kTextEncodingMacRoman            => 'MacRoman',
                $kTextEncodingMacJapanese         => 'macJapanese',
                $kTextEncodingMacChineseTrad      => 'MacChineseTrad',
                $kTextEncodingMacKorean           => 'MacKorean',
                $kTextEncodingMacArabic           => 'MacArabic',
                $kTextEncodingMacHebrew           => 'MacHebrew',
                $kTextEncodingMacGreek            => 'MacGreek',
                $kTextEncodingMacCyrillic         => 'MacCyrillic',
                $kTextEncodingMacThai             => 'MacThai',
                $kTextEncodingMacChineseSimp      => 'MacChineseSimp',
                $kTextEncodingMacCentralEurRoman  => 'MacCentralEurRoman',
                $kTextEncodingMacVietnamese       => 'MacVietnamese',
                $kTextEncodingMacSymbol           => 'MacSymbol',
                $kTextEncodingMacDingbats         => 'MacDingbats',
                $kTextEncodingMacTurkish          => 'MacTurkish',
                $kTextEncodingMacCroatian         => 'MacCroatian',
                $kTextEncodingMacIcelandic        => 'MacIcelandic',
                $kTextEncodingMacRomanian         => 'MacRomanian',
                $kTextEncodingMacFarsi            => 'MacFarsi',
                $kTextEncodingMacUkrainian        => 'MacUkrainian',
                $kTextEncodingISOLatin1           => 'iso-8859-1',
                $kTextEncodingISOLatin2           => 'iso-8859-2',
                $kTextEncodingISOLatin3           => 'iso-8859-3',
                $kTextEncodingISOLatin4           => 'iso-8859-4',
                $kTextEncodingISOLatinCyrillic    => 'iso-8859-5',
                $kTextEncodingISOLatinArabic      => 'iso-8859-6',
                $kTextEncodingISOLatinGreek       => 'iso-8859-7',
                $kTextEncodingISOLatinHebrew      => 'iso-8859-8',
                $kTextEncodingISOLatin5           => 'iso-8859-9',
                $kTextEncodingISOLatin6           => 'iso-8859-10',
                $kTextEncodingISOLatin7           => 'iso-8859-13',
                $kTextEncodingISOLatin8           => 'iso-8859-14',
                $kTextEncodingISOLatin9           => 'iso-8859-15',
                $kTextEncodingDOSLatinUS          => 'cp437',
                $kTextEncodingDOSGreek            => 'cp737',
                $kTextEncodingDOSBalticRim        => 'cp775',
                $kTextEncodingDOSLatin1           => 'cp850',
                $kTextEncodingDOSLatin2           => 'cp852',
                $kTextEncodingDOSCyrillic         => 'cp855',
                $kTextEncodingDOSTurkish          => 'cp857',
                $kTextEncodingDOSPortuguese       => 'cp860',
                $kTextEncodingDOSIcelandic        => 'cp861',
                $kTextEncodingDOSHebrew           => 'cp862',
                $kTextEncodingDOSArabic           => 'cp864',
                $kTextEncodingDOSNordic           => 'cp865',
                $kTextEncodingDOSGreek2           => 'cp869',
                $kTextEncodingDOSThai             => 'cp874',
                $kTextEncodingDOSJapanese         => 'cp932',
                $kTextEncodingDOSChineseSimplif   => 'cp936',
                $kTextEncodingDOSKorean           => 'cp949',
                $kTextEncodingDOSChineseTrad      => 'cp950',
                $kTextEncodingWindowsLatin1       => 'cp1252',
                $kTextEncodingWindowsLatin2       => 'cp1250',
                $kTextEncodingWindowsCyrillic     => 'cp1251',
                $kTextEncodingWindowsGreek        => 'cp1253',
                $kTextEncodingWindowsLatin5       => 'cp1254',
                $kTextEncodingWindowsHebrew       => 'cp1255',
                $kTextEncodingWindowsArabic       => 'cp1256',
                $kTextEncodingWindowsBalticRim    => 'cp1257',
                $kTextEncodingWindowsVietnamese   => 'cp1258',
                $kTextEncodingUS_ASCII            => 'US-ASCII',
                $kTextEncodingJIS_X0201_76        => 'jis0201-raw',
                $kTextEncodingJIS_X0208_83        => 'jis0208-raw',
              );

1;
# vim: ts=4
