package Net::AFP::TextEncodings;

use constant kTextEncodingMacRoman              => 0;
use constant kTextEncodingMacJapanese           => 1;
use constant kTextEncodingMacChineseTrad        => 2;
use constant kTextEncodingMacKorean             => 3;
use constant kTextEncodingMacArabic             => 4;
use constant kTextEncodingMacHebrew             => 5;
use constant kTextEncodingMacGreek              => 6;
use constant kTextEncodingMacCyrillic           => 7;
use constant kTextEncodingMacDevanagari         => 9;
use constant kTextEncodingMacGurmukhi           => 10;
use constant kTextEncodingMacGujarati           => 11;
use constant kTextEncodingMacOriya              => 12;
use constant kTextEncodingMacBengali            => 13;
use constant kTextEncodingMacTamil              => 14;
use constant kTextEncodingMacTelugu             => 15;
use constant kTextEncodingMacKannada            => 16;
use constant kTextEncodingMacMalayalam          => 17;
use constant kTextEncodingMacSinhalese          => 18;
use constant kTextEncodingMacBurmese            => 19;
use constant kTextEncodingMacKhmer              => 20;
use constant kTextEncodingMacThai               => 21;
use constant kTextEncodingMacLaotian            => 22;
use constant kTextEncodingMacGeorgian           => 23;
use constant kTextEncodingMacArmenian           => 24;
use constant kTextEncodingMacChineseSimp        => 25;
use constant kTextEncodingMacTibetan            => 26;
use constant kTextEncodingMacMongolian          => 27;
use constant kTextEncodingMacEthiopic           => 28;
use constant kTextEncodingMacCentralEurRoman    => 29;
use constant kTextEncodingMacVietnamese         => 30;
use constant kTextEncodingMacExtArabic          => 31;
use constant kTextEncodingMacSymbol             => 33;
use constant kTextEncodingMacDingbats           => 34;
use constant kTextEncodingMacTurkish            => 35;
use constant kTextEncodingMacCroatian           => 36;
use constant kTextEncodingMacIcelandic          => 37;
use constant kTextEncodingMacRomanian           => 38;
use constant kTextEncodingMacCeltic             => 39;
use constant kTextEncodingMacGaelic             => 40;
use constant kTextEncodingMacKeyboardGlyphs     => 41;
use constant kTextEncodingMacUnicode            => 126;
use constant kTextEncodingMacFarsi              => 140;
use constant kTextEncodingMacUkrainian          => 152;
use constant kTextEncodingMacInuit              => 236;
use constant kTextEncodingMacVT100              => 252;
use constant kTextEncodingMacHFS                => 255;
use constant kTextEncodingUnicodeDefault        => 256;
use constant kTextEncodingUnicodeV1_1           => 257;
use constant kTextEncodingISO10646_1993         => 257;
use constant kTextEncodingUnicodeV2_0           => 259;
use constant kTextEncodingUnicodeV2_1           => 259;
use constant kTextEncodingUnicodeV3_0           => 260;
use constant kTextEncodingISOLatin1             => 513;
use constant kTextEncodingISOLatin2             => 514;
use constant kTextEncodingISOLatin3             => 515;
use constant kTextEncodingISOLatin4             => 516;
use constant kTextEncodingISOLatinCyrillic      => 517;
use constant kTextEncodingISOLatinArabic        => 518;
use constant kTextEncodingISOLatinGreek         => 519;
use constant kTextEncodingISOLatinHebrew        => 520;
use constant kTextEncodingISOLatin5             => 521;
use constant kTextEncodingISOLatin6             => 522;
use constant kTextEncodingISOLatin7             => 525;
use constant kTextEncodingISOLatin8             => 526;
use constant kTextEncodingISOLatin9             => 527;
use constant kTextEncodingDOSLatinUS            => 1024;
use constant kTextEncodingDOSGreek              => 1029;
use constant kTextEncodingDOSBalticRim          => 1030;
use constant kTextEncodingDOSLatin1             => 1040;
use constant kTextEncodingDOSGreek1             => 1041;
use constant kTextEncodingDOSLatin2             => 1042;
use constant kTextEncodingDOSCyrillic           => 1043;
use constant kTextEncodingDOSTurkish            => 1044;
use constant kTextEncodingDOSPortuguese         => 1045;
use constant kTextEncodingDOSIcelandic          => 1046;
use constant kTextEncodingDOSHebrew             => 1047;
use constant kTextEncodingDOSCanadianFrench     => 1048;
use constant kTextEncodingDOSArabic             => 1049;
use constant kTextEncodingDOSNordic             => 1050;
use constant kTextEncodingDOSRussian            => 1051;
use constant kTextEncodingDOSGreek2             => 1052;
use constant kTextEncodingDOSThai               => 1053;
use constant kTextEncodingDOSJapanese           => 1056;
use constant kTextEncodingDOSChineseSimplif     => 1057;
use constant kTextEncodingDOSKorean             => 1058;
use constant kTextEncodingDOSChineseTrad        => 1059;
use constant kTextEncodingWindowsLatin1         => 1280;
use constant kTextEncodingWindowsANSI           => 1280;
use constant kTextEncodingWindowsLatin2         => 1281;
use constant kTextEncodingWindowsCyrillic       => 1282;
use constant kTextEncodingWindowsGreek          => 1283;
use constant kTextEncodingWindowsLatin5         => 1284;
use constant kTextEncodingWindowsHebrew         => 1285;
use constant kTextEncodingWindowsArabic         => 1286;
use constant kTextEncodingWindowsBalticRim      => 1287;
use constant kTextEncodingWindowsVietnamese     => 1288;
use constant kTextEncodingWindowsKoreanJohab    => 1296;
use constant kTextEncodingUS_ASCII              => 1536;
use constant kTextEncodingJIS_X0201_76          => 1568;
use constant kTextEncodingJIS_X0208_83          => 1569;
use constant kTextEncodingJIS_X0208_90          => 1570;

# Translation of known Mac charset IDs to Perl encoding IDs.
our %encmap = (
                kTextEncodingMacRoman()           => 'MacRoman',
                kTextEncodingMacJapanese()        => 'macJapanese',
                kTextEncodingMacChineseTrad()     => 'MacChineseTrad',
                kTextEncodingMacKorean()          => 'MacKorean',
                kTextEncodingMacArabic()          => 'MacArabic',
                kTextEncodingMacHebrew()          => 'MacHebrew',
                kTextEncodingMacGreek()           => 'MacGreek',
                kTextEncodingMacCyrillic()        => 'MacCyrillic',
                kTextEncodingMacThai()            => 'MacThai',
                kTextEncodingMacChineseSimp()     => 'MacChineseSimp',
                kTextEncodingMacCentralEurRoman() => 'MacCentralEurRoman',
                kTextEncodingMacVietnamese()      => 'MacVietnamese',
                kTextEncodingMacSymbol()          => 'MacSymbol',
                kTextEncodingMacDingbats()        => 'MacDingbats',
                kTextEncodingMacTurkish()         => 'MacTurkish',
                kTextEncodingMacCroatian()        => 'MacCroatian',
                kTextEncodingMacIcelandic()       => 'MacIcelandic',
                kTextEncodingMacRomanian()        => 'MacRomanian',
                kTextEncodingMacFarsi()           => 'MacFarsi',
                kTextEncodingMacUkrainian()       => 'MacUkrainian',
                kTextEncodingISOLatin1()          => 'iso-8859-1',
                kTextEncodingISOLatin2()          => 'iso-8859-2',
                kTextEncodingISOLatin3()          => 'iso-8859-3',
                kTextEncodingISOLatin4()          => 'iso-8859-4',
                kTextEncodingISOLatinCyrillic()   => 'iso-8859-5',
                kTextEncodingISOLatinArabic()     => 'iso-8859-6',
                kTextEncodingISOLatinGreek()      => 'iso-8859-7',
                kTextEncodingISOLatinHebrew()     => 'iso-8859-8',
                kTextEncodingISOLatin5()          => 'iso-8859-9',
                kTextEncodingISOLatin6()          => 'iso-8859-10',
                kTextEncodingISOLatin7()          => 'iso-8859-13',
                kTextEncodingISOLatin8()          => 'iso-8859-14',
                kTextEncodingISOLatin9()          => 'iso-8859-15',
                kTextEncodingDOSLatinUS()         => 'cp437',
                kTextEncodingDOSGreek()           => 'cp737',
                kTextEncodingDOSBalticRim()       => 'cp775',
                kTextEncodingDOSLatin1()          => 'cp850',
                kTextEncodingDOSLatin2()          => 'cp852',
                kTextEncodingDOSCyrillic()        => 'cp855',
                kTextEncodingDOSTurkish()         => 'cp857',
                kTextEncodingDOSPortuguese()      => 'cp860',
                kTextEncodingDOSIcelandic()       => 'cp861',
                kTextEncodingDOSHebrew()          => 'cp862',
                kTextEncodingDOSArabic()          => 'cp864',
                kTextEncodingDOSNordic()          => 'cp865',
                kTextEncodingDOSGreek2()          => 'cp869',
                kTextEncodingDOSThai()            => 'cp874',
                kTextEncodingDOSJapanese()        => 'cp932',
                kTextEncodingDOSChineseSimplif()  => 'cp936',
                kTextEncodingDOSKorean()          => 'cp949',
                kTextEncodingDOSChineseTrad()     => 'cp950',
                kTextEncodingWindowsLatin1()      => 'cp1252',
                kTextEncodingWindowsLatin2()      => 'cp1250',
                kTextEncodingWindowsCyrillic()    => 'cp1251',
                kTextEncodingWindowsGreek()       => 'cp1253',
                kTextEncodingWindowsLatin5()      => 'cp1254',
                kTextEncodingWindowsHebrew()      => 'cp1255',
                kTextEncodingWindowsArabic()      => 'cp1256',
                kTextEncodingWindowsBalticRim()   => 'cp1257',
                kTextEncodingWindowsVietnamese()  => 'cp1258',
                kTextEncodingUS_ASCII()           => 'US-ASCII',
                kTextEncodingJIS_X0201_76()       => 'jis0201-raw',
                kTextEncodingJIS_X0208_83()       => 'jis0208-raw',
              );

1;
# vim: ts=4
