=head1 NAME

Net::AFP::UAMs - AFP authentication helper functions

=head1 DESCRIPTION

This package contains convenience functions for calling User
Authentication Method code on an AFP connection.

=head1 UAM STRINGS

AFP can support multiple UAMs. The modules for the UAMs are automatically
enumerated when this module is loaded. See the C<Net/AFP/UAMs/>
subdirectory for the available UAM modules. The supported UAM list is
available in the structure returned from the L<Net::AFP/FPGetSrvrInfo()>
call (the same structure is returned from the L<Net::DSI/DSIGetStatus>
and L<Net::Atalk::ASP/SPGetStatus> calls).

=head1 FUNCTIONS

=over

=item GuestAuth()

Perform simple anonymous (guest) authentication with the server.

=over

=item $session

An object derived from Net::AFP, for an active but not yet authenticated
AFP server connection.

=item $AFPVersion

A string containing the AFP version identifier for the highest protocol
version both sides can agree on. See
L<Net::AFP::Versions/GetPreferredVersion()> for more information.

=back

=item PasswordAuth()

Perform password-based authentication with the server.

=over

=item $session

An object derived from Net::AFP, for an active but not yet authenticated
AFP server connection.

=item $AFPVersion

A string containing the AFP version identifier for the highest protocol
version both sides can agree on. See
L<Net::AFP::Versions/GetPreferredVersion()> for more information.

=item $SupportedUAMs

An array ref containing the list of supported UAMs which should be tried.
Normally this should be the 'UAMs' structure element returned from
L<Net::AFP/FPGetSrvrInfo>.

=item $UserName

A string containing the username to log in as.

=item $PwCallback

A subroutine reference which is to be used to acquire the user's password.

=back

=item ChangePassword()

=over

=item $session

An object derived from Net::AFP, for an active but not yet authenticated
AFP server connection.

=item $SupportedUAMs

An array ref containing the list of supported UAMs which should be tried.
Normally this should be the 'UAMs' structure element returned from
L<Net::AFP/FPGetSrvrInfo>.

=item $UserName

A string containing the username whose password is to be changed. Ignored
as of AFP 3.0.

=item $OldPW

A string containing the user's current password.

=item $NewPW

A string containing the new password to be set for the user.

=back

=back

=head1 AUTHOR

Derrik Pates <demon@now.ai>

=head1 SEE ALSO

C<Net::AFP>

=cut
